apiVersion: v1
kind: Service
metadata:
  name: hms-bed-monitor-svc
spec:
  selector:
    app: hms-bed-monitor-pod
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-bed-monitor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-bed-monitor-pod
  template:
    metadata:
      labels:
        app: hms-bed-monitor-pod
    spec:
      serviceAccountName: hms-monitor-sa
      containers:
      - name: hms-bed-monitor
        image: somnathbm/hms-bed-monitor-svc:v0.0.5
        ports:
        - containerPort: 8080
