name: go app deploy
run-name: go app deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
    - name: Install deps
      id: deps
      run: |
        go get .
        go build -o ./dist/hospi_bed_stats.sh > "$GITHUB_OUTPUT"
    outputs:
      script: ${{ steps.deps.outputs}}