name: HMS bed monitor service deploy
run-name: HMS bed monitor service deploy
on:
  push:
    tags:
      - v*
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build & publish the image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: somnathbm/hms-bed-monitor-svc:${{github.ref_name}}
  deploy_to_eks:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}
    - name: Update kubeconfig using aws eks cli
      run: aws eks update-kubeconfig --name test-hospi-beds-cluster --region ${{secrets.AWS_REGION}}