resources:
- ../base

namespace: hms-prod
nameSuffix: -prod

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hms-bed-monitor-depl
    path: patch-service-account.yaml